# Generated by Django 5.2.15 on 2026-09-14 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceGroupSyncConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("sync_on_login", models.BooleanField(default=True)),
                ("offline_sync", models.BooleanField(default=False)),
                ("auto_remove", models.BooleanField(default=False)),
                ("group_attribute_key", models.CharField(default="groups", max_length=255)),
                (
                    "default_workspace_role",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(20, "Admin"), (15, "Member"), (5, "Guest")], null=True
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="group_sync_config", to="db.workspace"
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Group Sync Config",
                "verbose_name_plural": "Workspace Group Sync Configs",
                "db_table": "workspace_group_sync_configs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="GroupSyncMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("role", models.PositiveSmallIntegerField(choices=[(20, "Admin"), (15, "Member"), (5, "Guest")])),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sync_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sync_memberships",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sync_memberships",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Sync Membership",
                "verbose_name_plural": "Group Sync Memberships",
                "db_table": "group_sync_memberships",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("workspace", "project", "member"),
                        name="group_sync_membership_unique_project_member_when_deleted_at_null",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True), ("project__isnull", True)),
                        fields=("workspace", "member"),
                        name="group_sync_membership_unique_workspace_member_when_deleted_at_null",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectGroupRoleMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.PositiveSmallIntegerField(choices=[(20, "Admin"), (15, "Member"), (5, "Guest")], default=15),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_role_mappings",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_group_role_mappings",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Group Role Mapping",
                "verbose_name_plural": "Project Group Role Mappings",
                "db_table": "project_group_role_mappings",
                "ordering": ("group_name",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("workspace", "project", "group_name"),
                        name="project_group_role_mapping_unique_project_group_when_deleted_at_null",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True), ("project__isnull", True)),
                        fields=("workspace", "group_name"),
                        name="project_group_role_mapping_unique_all_projects_group_when_deleted_at_null",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceGroupRoleMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.PositiveSmallIntegerField(choices=[(20, "Admin"), (15, "Member"), (5, "Guest")], default=15),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_role_mappings",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Group Role Mapping",
                "verbose_name_plural": "Workspace Group Role Mappings",
                "db_table": "workspace_group_role_mappings",
                "ordering": ("group_name",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("workspace", "group_name"),
                        name="workspace_group_role_mapping_unique_group_when_deleted_at_null",
                    )
                ],
                "unique_together": {("workspace", "group_name", "deleted_at")},
            },
        ),
    ]
